services:
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - '6379:6379'

  app1:
    build: ./server
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - UPDATE_INTERVAL=500
    volumes:
      - ./client:/usr/src/client:ro
    depends_on:
      - redis

  app2:
    build: ./server
    environment:
      - PORT=3001
      - REDIS_HOST=redis
      - UPDATE_INTERVAL=500
    volumes:
      - ./client:/usr/src/client:ro
    depends_on:
      - redis

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - app1
      - app2
    ports:
      - '8080:8080'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro